### ISSUE TITLE
Implement cosmic npm rather than fetch for image GET

### ISSUE THREAD

**Issue by kemiljk** [kemiljk/better-logos-figma#10]
Means we should be able to easily use .env for creds then too?

**Comment by kemiljk** [comment]
We're already using this in the image upload script, can we repurpose that to handle it UI-side too? @neefrehman 

```
import Cosmic from "cosmicjs";

const COSMIC_READ_KEY = "MRVaU7qPspQBu7jC4TjrRwMrVfkIfRLwE4APIUGkjuDXgDQKII";
const COSMIC_WRITE_KEY = "2x1X3rPy5Rd3bB1ipl4gGIV0T2QcsuheLwh3GinJfolWXg5DaO";

const api = Cosmic();
const bucket = api.bucket({
    slug: "better-logos-production",
    read_key: COSMIC_READ_KEY,
    write_key: COSMIC_WRITE_KEY
});
```

**Comment by kemiljk** [comment]
I literally thought about implementing the Projects stuff last night! Same brain @neefrehman 🥇

**Comment by neefrehman** [comment]
this will be possible once we move to webpack, but I actually think we should stick with the current `fetch` method in the UI. We don't really need the benefits that the npm package gives us since we're just getting JSON, and it avoids users having to download ~30kb of javascript whenever they open the plugin, better for load times and for the planet :)

**Comment by neefrehman** [comment]
on `.env`, we could still use that with our fetch method, but I should note that `.env` only lets us keep the API keys out of our source files. they will still end up in the output's javascript bundle. there's no way we can keep any variables required for the plugin from being in there.

Usually to get around this people would hide the fetching logic behind their own API, and query that from the frontend, but I think that we can't even do that with a Figma plugin since we can't use IPs to authenticate? this is why many figma plugins that require remote data ask people to generate their own keys. there's probably a better solution, I just don't know what it is!

Maybe we should separate security into another ticket so we can keep the conversation in one place? @kemiljk

**Comment by kemiljk** [comment]
Okay cool @neefrehman -> I've moved this comment over to a new Security issue so it can be looked at down the line :). I agree, let's maintain our fetch method for now and I'll close this Issue.
