### ISSUE TITLE
Split type & company name for searching

### ISSUE THREAD

**Issue by neefrehman** [kemiljk/better-logos-figma#25]
~We should set the `alt` attribute for each logo to be the same as the title, and instead use a `data-type` attribute to do the filtering.~

EDIT: updating this issue as I realise that the alt is actually what it should be! It just contains the `type`. I think we should split the type and brand name up, however? And have a different attribute to search for?

Currently, if you filter for `white` and type "white" (or any of its characters) in the search bar, you will just get a grid of all the logos, as they all contain that string. Also if a brand has "white" in it's name, all of it's colours will show up when filtering for "white"

To solve this we could have another datapoint in the cms that's just the company name? we would use this for searching, the type for filtering, and both for the image alt:

```
<img alt={title_with_type} data-type={type} data-brand={brand} />
```

**Comment by kemiljk** [comment]
So... the title is already fetchable and searchable, so maybe the answer is to remove the reference to the type in the title as I don't think this is strictly necessary (it just helps searchability if viewing the CMS).

Alternatively, like you say, we could add another plain text field for title and fetch that instead for our title reference? We can add that by just adding the metafield to the script directly and it would update all the items in the CMS (unless it returns too early because another metafield matches?).

My thought would be to add the following (but my TypeScript sucks so I've had little luck doing this myself to test (I get an overload call on the getLogosFromFs at line 90 after I've included `currentCompany` in the `interface`):
```
{
                type: "text",
                title: "Brand name",
                key: "brand_name",
                value: currentCompany
            },
```
